#!/bin/bash
#

cd /root/nox/NoxSpheraWebApp

target/universal/stage/bin/commandcontrolcentre -Dhttp.port=80 -Dconfig.file=conf/application.prod.conf
#play start -Dhttp.port=80 -Dconfig.file=conf/application.prod.conf

echo Servizio in esecuzione!

